### ISSUE TITLE
Update to Couchbase Client 2.2.8

### ISSUE THREAD

**Issue by agyan5** [smartmachine/dropwizard-couchbase#13]
Wanted to check if there is a version upgrade planned for client 2.2.8 anytime soon.

**Comment by knutster** [comment]
Been a while since I looked at this, thanks for the bump and will do my best!

**Comment by knutster** [comment]
@agyan2 Have a look, I have updated to client 2.4.5 and dropwizard 1.1.1.  I can't vouch for it 100% yet, I will do some integration testing over the weekend.

**Comment by agyan5** [comment]
Closing
